// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewqoryvormjvzumqaarf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cW9yeXZvcm1qdnp1bXFhYXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzM1OTksImV4cCI6MjA3NjEwOTU5OX0.-An8LltbELuEY4yrR-kKayrSuqd3D5R8WuuDzq2_ckA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});